name: Generate Snake Animation

on:
  push:
    branches:
      malobr
  schedule:
    - cron: "0 */12 * * *"  # Executar a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # Substitua 'requirements.txt' pelo nome do seu arquivo de requisitos se aplicável

      - name: Generate Snake Animation
        id: generate-snake
        run: |
          python generate_snake.py  # Substitua pelo comando para gerar a animação da cobra

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: path/to/your/svg/file  # Substitua pelo caminho para o seu arquivo SVG

